spring:
  application:
    name: login-service
  datasource:
    url: jdbc:mysql://localhost:3306/EFSNATDB?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: mysql
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect  
        format_sql: true 
    hibernate:
      ddl-auto: update

server:
  port: 9103


